/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/kkl-prototype-adjusted.glb');
	return (
		<group ref={group} {...props} dispose={null} scale={0.5}>
			<mesh geometry={nodes.windows.geometry} material={materials.windows} />
			<mesh
				geometry={nodes.outer_walls.geometry}
				material={materials.outer_walls}
			/>
			<mesh geometry={nodes.stairs.geometry} material={materials.stairs} />
			<mesh geometry={nodes.fence.geometry} material={materials.fence} />
			<mesh geometry={nodes.balcony.geometry} material={materials.balcony} />
			<mesh geometry={nodes.doors.geometry} material={materials.doors} />
			<mesh geometry={nodes.roof.geometry} material={materials.roof} />
			<mesh geometry={nodes.floor.geometry} material={materials.floor} />
			<mesh
				geometry={nodes.inner_walls.geometry}
				material={materials.inner_walls}
			/>
		</group>
	);
}

useGLTF.preload('/kkl-prototype-adjusted.glb');
